### ISSUE TITLE
android 源码编译的很坑爹，20几分中才搞好

### ISSUE THREAD

**Issue by suncunhu** [openproject/ganchai#3]
最后还报这么个错误
Cannot change configuration ':classpath' after it has been resolved.

**Comment by suncunhu** [comment]
搞定了，可我不理解为什么要在ex{}写sdk版本 ？

**Comment by openproject** [comment]
ext方便全局控制，假如后面会加一些单独的ｌｉｂｒａｒｙ功能模块，可以全局控制

**Comment by openproject** [comment]
第一次编译需要下载一些第三方库，可能花了很多时间
